# Generated by Django 4.2.2 on 2023-06-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_seller",
            field=models.BooleanField(default=False),
        ),
    ]
