# Generated by Django 4.2.2 on 2023-06-26 08:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_person_is_seller"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="is_seller",
        ),
        migrations.AddField(
            model_name="person",
            name="join_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sale_date", models.DateField(default=datetime.date.today)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="order.person"
                    ),
                ),
            ],
        ),
    ]
